# Generated by Django 3.2 on 2021-04-28 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sigs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('section', models.CharField(default='A', max_length=1)),
                ('college_email_id', models.EmailField(max_length=254, verbose_name='College Email')),
                ('contact_number', models.ImageField(blank=True, null=True, upload_to=None)),
                ('experience', models.TextField(blank=True, default='')),
                ('projects', models.TextField(blank=True, default='')),
                ('member_type', models.CharField(blank=True, default='SIG MEMBER', max_length=20)),
                ('is_acm_team', models.BooleanField(default=False, null=True)),
                ('sigs', models.ManyToManyField(blank=True, to='sigs.SpecialInterestGroup')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ACMTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Management', max_length=50)),
                ('joined_on', models.DateField()),
                ('membership_type', models.CharField(max_length=50)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.member', verbose_name='ACM Team Member')),
            ],
        ),
    ]
