# Generated by Django 3.2 on 2021-05-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('CHAIR', 'CHAIR'), ('VICE_CHAIR', 'VICE CHAIR'), ('PRIME_CORE', 'PRIME CORE'), ('CORE', 'CORE'), ('HEAD', 'SIG HEAD'), ('SUB_HEAD', 'SIG SUBHEAD'), ('COORDINATOR', 'COORDINATOR'), ('SUB_COORDINATOR', 'SUB COORDINATOR'), ('MEMBER', 'SIG MEMBER')], default='MEMBER', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='designation',
            field=models.CharField(default='SIG MEMBER', max_length=50),
        ),
    ]
