# Generated by Django 3.2 on 2021-04-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0002_auto_20210428_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='submissions',
            field=models.ManyToManyField(blank=True, to='tasks.TaskSubmission'),
        ),
    ]
