# Generated by Django 3.2 on 2021-05-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigs', '0004_remove_specialinterestgroup_members'),
        ('users', '0006_alter_member_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='submissions',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sigs',
        ),
        migrations.AddField(
            model_name='member',
            name='sigs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sigs_joined', to='sigs.specialinterestgroup'),
        ),
    ]
