# Generated by Django 3.2 on 2021-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigs', '0004_remove_specialinterestgroup_members'),
        ('users', '0008_auto_20210505_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sigs',
            field=models.ManyToManyField(blank=True, related_name='sigs_joined', to='sigs.SpecialInterestGroup'),
        ),
    ]
