# Generated by Django 3.2 on 2021-05-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_member_sigs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmteammember',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, choices=[('CHAIR', 'CHAIR'), ('VICE_CHAIR', 'VICE CHAIR'), ('PRIME_CORE', 'PRIME CORE'), ('CORE', 'CORE'), ('HEAD', 'SIG HEAD'), ('SUB_HEAD', 'SIG SUBHEAD'), ('COORDINATOR', 'COORDINATOR'), ('SUB_COORDINATOR', 'SUB COORDINATOR'), ('MEMBER', 'SIG MEMBER')], default='MEMBER', max_length=30),
        ),
    ]
