# Generated by Django 3.2 on 2021-05-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210505_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, default='Write something about yourself here'),
        ),
        migrations.AlterField(
            model_name='acmteammember',
            name='joined_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='roll_no',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
