# Generated by Django 3.2 on 2021-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210506_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, default='/media/images/profile/default.jpg', upload_to='images/profile/'),
        ),
    ]
