# Generated by Django 3.2 on 2021-05-04 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigs', '0003_specialinterestgroup_image'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='files',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='code_files',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='output_files',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sigs.specialinterestgroup'),
        ),
    ]
