# Generated by Django 3.2 on 2021-04-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='resources',
        ),
        migrations.AddField(
            model_name='task',
            name='resources',
            field=models.ManyToManyField(blank=True, to='tasks.LearningResources'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='submissions',
        ),
        migrations.AddField(
            model_name='task',
            name='submissions',
            field=models.ManyToManyField(blank=True, to='tasks.TaskSubmission'),
        ),
    ]
