# Generated by Django 3.2 on 2021-05-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_member_profile_image'),
        ('tasks', '0002_auto_20210505_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.member'),
        ),
    ]
