# Generated by Django 3.2 on 2021-05-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasksubmission_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_for',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task'),
        ),
    ]
