# Generated by Django 3.2 on 2021-05-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_member_profile_image'),
        ('tasks', '0004_alter_tasksubmission_submitted_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_submission', to='users.member'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_submission', to='tasks.task'),
        ),
    ]
