# Generated by Django 3.2 on 2021-05-16 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_starter_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='resources',
        ),
        migrations.AddField(
            model_name='learningresource',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.task', verbose_name='Learning Resource'),
        ),
    ]
