# Generated by Django 3.2 on 2021-05-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20210516_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='type',
            field=models.CharField(choices=[('Article', 'ARTICLE'), ('Video', 'VIDEO'), ('Blog', 'BLOG'), ('Tool', 'TOOL'), ('Demo', 'DEMO')], max_length=20),
        ),
    ]
