# Generated by Django 3.2 on 2021-05-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_learningresource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='status',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='grading_status',
            field=models.BooleanField(choices=[(True, 'GRADED'), (False, 'PENDING')], default=False),
        ),
    ]
