# Generated by Django 3.2 on 2021-04-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialInterestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('session', models.IntegerField()),
                ('group_link', models.URLField(blank=True, null=True)),
                ('syllabus_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
