# Generated by Django 3.2 on 2021-04-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sigs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialinterestgroup',
            name='management',
            field=models.ManyToManyField(to='users.ACMTeamMember'),
        ),
        migrations.AddField(
            model_name='specialinterestgroup',
            name='members',
            field=models.ManyToManyField(blank=True, to='users.Member'),
        ),
    ]
