# Generated by Django 3.2 on 2021-05-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialinterestgroup',
            name='management',
            field=models.ManyToManyField(blank=True, to='users.Member'),
        ),
    ]
