# Generated by Django 3.2 on 2021-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_member_profile_image'),
        ('sigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialinterestgroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='specialinterestgroup',
            name='management',
            field=models.ManyToManyField(blank=True, to='users.ACMTeamMember'),
        ),
    ]
