# Generated by Django 3.2 on 2021-05-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigs', '0002_auto_20210504_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialinterestgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/sigs/'),
        ),
    ]
