# Generated by Django 3.2 on 2021-05-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigs', '0003_specialinterestgroup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialinterestgroup',
            name='members',
        ),
    ]
